add section check elementary_report.html

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -269,6 +269,15 @@ jobs:
           ls -lR target/ # DEBUG STEP: List the contents of the target directory
           echo "End of target directory listing."
 
+      - name: Ensure Elementary report exists # Check for file existence
+        run: |
+          REPORT_PATH="${{ vars.DBT_FOLDER_NAME }}/target/elementary_report.html"
+          if [ ! -f "$REPORT_PATH" ]; then
+            echo "Error: Elementary report not found at $REPORT_PATH!"
+            exit 1
+          fi
+          echo "Elementary report found at $REPORT_PATH."
+
       - name: Upload Elementary Report as Artifact
         uses: actions/upload-artifact@v4
         with:
